[profile.default]
# Project
# https://book.getfoundry.sh/reference/config/project
src = 'contracts'
test = 'test'
no_match_test = "testDiff"
out = 'out'
libs = [
  'node_modules',
  'lib'
]
cache = true
cache_path = 'cache'
force = false

# Compiler
# https://book.getfoundry.sh/reference/config/solidity-compiler
libraries = []
auto_detect_solc = true

# 2462: Visibility for constructor is ignored
ignored_error_codes = [2462]
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = 'ipfs'

# Testing
# https://book.getfoundry.sh/reference/config/testing
verbosity = 0
ffi = true
fs_permissions = [
  { access = "read", path = "../"},
  { access = "read", path = "./out" }
]
ignored_warnings_from = [
  "test",
  "contracts/interfaces/IMockFBeanstalk.sol",
  "contracts/mocks/"
]
gas_reports = ['*']
 # Cache to `$HOME/.foundry/cache/<chain id>/<block number>`.
no_storage_caching = false
 
[profile.differential]
match_test = "testDiff"
no_match_test = "a^"

# Formatter
# https://book.getfoundry.sh/reference/config/formatter
# ...pass...
[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'


