# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[profile.default]
src = 'contracts'
out = 'artifacts'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=lib/forge-std/src/',
    'hardhat/=node_modules/hardhat/',
]

rpc_storage_caching = { chains = 'all', endpoints = 'all' }