name: Subgraph Basin

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "projects/subgraph-basin/**"

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install The Graph CLI
        run: npm install -g @graphprotocol/graph-cli
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Generate Subgraph Code
        run: yarn codegen
        working-directory: projects/subgraph-basin

      - name: Build Subgraph
        run: yarn build
        working-directory: projects/subgraph-basin
  test:
    runs-on: macos-latest
    name: Test
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install The Graph CLI
        run: npm install -g @graphprotocol/graph-cli
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Generate Subgraph Code
        run: yarn codegen
        working-directory: projects/subgraph-basin

      - name: Run Tests
        run: yarn test
        working-directory: projects/subgraph-basin
